select-supported: true
insert-supported: true
update-supported: true
delete-supported: true
count-supported: true
count-strategy: ACTUAL

search-supported: false
aggregate-supported: false

record-id-type: NUMBER

filterable-fields:
  - id
  - opportunity_id
  - account_id
  - stage_name

sortable-fields:
  - id
  - close_date
  - amount
