name: "CRM Data sugimotok_Opportunity"
primary-key:
  kintone-field-id: id
  jdbc-column: Id
columns:
  - kintone-field-id: opportunity_id
    jdbc-column: Id1
    type: TEXT
  - kintone-field-id: name
    jdbc-column: Name
    type: TEXT
  - kintone-field-id: stage_name
    jdbc-column: StageName
    type: TEXT
  - kintone-field-id: amount
    jdbc-column: Amount
    type: NUMBER
  - kintone-field-id: probability
    jdbc-column: Probability
    type: NUMBER
  - kintone-field-id: close_date
    jdbc-column: CloseDate
    type: DATETIME
  - kintone-field-id: account_id
    jdbc-column: AccountId
    type: TEXT
  - kintone-field-id: lead_source
    jdbc-column: LeadSource
    type: TEXT
