name: "Account"
primary-key:
  kintone-field-id: "id"
  jdbc-column: "Id"
columns:
- kintone-field-id: "is_deleted"
  jdbc-column: "IsDeleted"
  type: "TEXT"
- kintone-field-id: "master_record_id"
  jdbc-column: "MasterRecordId"
  type: "TEXT"
- kintone-field-id: "name"
  jdbc-column: "Name"
  type: "TEXT"
- kintone-field-id: "type"
  jdbc-column: "Type"
  type: "TEXT"
- kintone-field-id: "parent_id"
  jdbc-column: "ParentId"
  type: "TEXT"
- kintone-field-id: "billing_street"
  jdbc-column: "BillingStreet"
  type: "TEXT"
- kintone-field-id: "billing_city"
  jdbc-column: "BillingCity"
  type: "TEXT"
- kintone-field-id: "billing_state"
  jdbc-column: "BillingState"
  type: "TEXT"
- kintone-field-id: "billing_postal_code"
  jdbc-column: "BillingPostalCode"
  type: "TEXT"
- kintone-field-id: "billing_country"
  jdbc-column: "BillingCountry"
  type: "TEXT"
- kintone-field-id: "billing_state_code"
  jdbc-column: "BillingStateCode"
  type: "TEXT"
- kintone-field-id: "billing_country_code"
  jdbc-column: "BillingCountryCode"
  type: "TEXT"
- kintone-field-id: "billing_latitude"
  jdbc-column: "BillingLatitude"
  type: "NUMBER"
- kintone-field-id: "billing_longitude"
  jdbc-column: "BillingLongitude"
  type: "NUMBER"
- kintone-field-id: "billing_geocode_accuracy"
  jdbc-column: "BillingGeocodeAccuracy"
  type: "TEXT"
- kintone-field-id: "shipping_street"
  jdbc-column: "ShippingStreet"
  type: "TEXT"
- kintone-field-id: "shipping_city"
  jdbc-column: "ShippingCity"
  type: "TEXT"
- kintone-field-id: "shipping_state"
  jdbc-column: "ShippingState"
  type: "TEXT"
- kintone-field-id: "shipping_postal_code"
  jdbc-column: "ShippingPostalCode"
  type: "TEXT"
- kintone-field-id: "shipping_country"
  jdbc-column: "ShippingCountry"
  type: "TEXT"
- kintone-field-id: "shipping_state_code"
  jdbc-column: "ShippingStateCode"
  type: "TEXT"
- kintone-field-id: "shipping_country_code"
  jdbc-column: "ShippingCountryCode"
  type: "TEXT"
- kintone-field-id: "shipping_latitude"
  jdbc-column: "ShippingLatitude"
  type: "NUMBER"
- kintone-field-id: "shipping_longitude"
  jdbc-column: "ShippingLongitude"
  type: "NUMBER"
- kintone-field-id: "shipping_geocode_accuracy"
  jdbc-column: "ShippingGeocodeAccuracy"
  type: "TEXT"
- kintone-field-id: "phone"
  jdbc-column: "Phone"
  type: "TEXT"
- kintone-field-id: "fax"
  jdbc-column: "Fax"
  type: "TEXT"
- kintone-field-id: "account_number"
  jdbc-column: "AccountNumber"
  type: "TEXT"
- kintone-field-id: "website"
  jdbc-column: "Website"
  type: "TEXT"
- kintone-field-id: "photo_url"
  jdbc-column: "PhotoUrl"
  type: "TEXT"
- kintone-field-id: "sic"
  jdbc-column: "Sic"
  type: "TEXT"
- kintone-field-id: "industry"
  jdbc-column: "Industry"
  type: "TEXT"
- kintone-field-id: "annual_revenue"
  jdbc-column: "AnnualRevenue"
  type: "NUMBER"
- kintone-field-id: "number_of_employees"
  jdbc-column: "NumberOfEmployees"
  type: "NUMBER"
- kintone-field-id: "ownership"
  jdbc-column: "Ownership"
  type: "TEXT"
- kintone-field-id: "ticker_symbol"
  jdbc-column: "TickerSymbol"
  type: "TEXT"
- kintone-field-id: "description"
  jdbc-column: "Description"
  type: "TEXT"
- kintone-field-id: "rating"
  jdbc-column: "Rating"
  type: "TEXT"
- kintone-field-id: "site"
  jdbc-column: "Site"
  type: "TEXT"
- kintone-field-id: "owner_id"
  jdbc-column: "OwnerId"
  type: "TEXT"
- kintone-field-id: "created_date"
  jdbc-column: "CreatedDate"
  type: "DATETIME"
- kintone-field-id: "created_by_id"
  jdbc-column: "CreatedById"
  type: "TEXT"
- kintone-field-id: "last_modified_by_id"
  jdbc-column: "LastModifiedById"
  type: "TEXT"
- kintone-field-id: "last_activity_date"
  jdbc-column: "LastActivityDate"
  type: "DATETIME"
- kintone-field-id: "last_viewed_date"
  jdbc-column: "LastViewedDate"
  type: "DATETIME"
- kintone-field-id: "last_referenced_date"
  jdbc-column: "LastReferencedDate"
  type: "DATETIME"
- kintone-field-id: "jigsaw"
  jdbc-column: "Jigsaw"
  type: "TEXT"
- kintone-field-id: "jigsaw_company_id"
  jdbc-column: "JigsawCompanyId"
  type: "TEXT"
- kintone-field-id: "clean_status"
  jdbc-column: "CleanStatus"
  type: "TEXT"
- kintone-field-id: "account_source"
  jdbc-column: "AccountSource"
  type: "TEXT"
- kintone-field-id: "duns_number"
  jdbc-column: "DunsNumber"
  type: "TEXT"
- kintone-field-id: "tradestyle"
  jdbc-column: "Tradestyle"
  type: "TEXT"
- kintone-field-id: "naics_code"
  jdbc-column: "NaicsCode"
  type: "TEXT"
- kintone-field-id: "naics_desc"
  jdbc-column: "NaicsDesc"
  type: "TEXT"
- kintone-field-id: "year_started"
  jdbc-column: "YearStarted"
  type: "TEXT"
- kintone-field-id: "sic_desc"
  jdbc-column: "SicDesc"
  type: "TEXT"
- kintone-field-id: "dandb_company_id"
  jdbc-column: "DandbCompanyId"
  type: "TEXT"
- kintone-field-id: "operating_hours_id"
  jdbc-column: "OperatingHoursId"
  type: "TEXT"
- kintone-field-id: "customerpriority__c"
  jdbc-column: "CustomerPriority__c"
  type: "TEXT"
- kintone-field-id: "sla__c"
  jdbc-column: "SLA__c"
  type: "TEXT"
- kintone-field-id: "active__c"
  jdbc-column: "Active__c"
  type: "TEXT"
- kintone-field-id: "numberoflocations__c"
  jdbc-column: "NumberofLocations__c"
  type: "NUMBER"
- kintone-field-id: "upsellopportunity__c"
  jdbc-column: "UpsellOpportunity__c"
  type: "TEXT"
- kintone-field-id: "slaserialnumber__c"
  jdbc-column: "SLASerialNumber__c"
  type: "TEXT"
- kintone-field-id: "slaexpirationdate__c"
  jdbc-column: "SLAExpirationDate__c"
  type: "DATETIME"
- kintone-field-id: "system_modstamp"
  jdbc-column: "SystemModstamp"
  type: "DATETIME"
- kintone-field-id: "last_modified_date"
  jdbc-column: "LastModifiedDate"
  type: "DATETIME"